### ISSUE TITLE
Allow Quantity to be expressed in formulas or decimals

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/magic-spreedsheet#1]
Column D in the "Budget" sheet is dedicated to entering the quantity in which people's time is measured. Currently, it displays the error message "There was a problem. Quantity must be in number", if:

* I enter a formula. For example: "Alice worked 20% of her time for 3 months, so I am going to input `=3*.2`"
* I enter a decimal. For example: "Bob is going to be working three quarters of a day, so let's input `0.75`". 

These are legitimate use cases for this column, so I claim the restriction on formulas (especially) and  decimals is a bug. 

My sandbox is [here](https://docs.google.com/spreadsheets/d/145avvcb6wno3tKGsUO1kYzp4kE5PjhA-iCuVcq5zKY8/edit#gid=2147433014).

**Comment by tanius** [comment]
This has been fixed during development at some time in the past.

I just tested it again, and it works: file "[Budget Template v3](https://docs.google.com/spreadsheets/d/1TYD2i8uycMb8pELSHG5T2wH1sJMP0T3RQsQ_iscKIYM/edit#gid=2147433014)", sheet "Cost", column "Qty".
