### ISSUE TITLE
Allow forecast of cash flow

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/magic-spreedsheet#2]
Right now, it is not clear how I can plan for money to come in. Because:

* The end date in the "Overview" sheet (B4) is computed from the "Status" sheet.
* Adding an invoice with 100% probability in the "Status" sheet does take care of the end date of the project, but still I do not see the chart going up.

**Comment by tanius** [comment]
Cash flow forecasting is implemented in the most recent version (Budget Spreadsheet v3) now. Which is not yet here in the repository but so far only available as a Google Spreadsheet, but we'll publish it here as well shortly.
