### ISSUE TITLE
Check status against current date

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/magic-spreedsheet#3]
## Context

Many projects as encoded in their Magic Budgets are active in the present, but their end date is known ([example](https://docs.google.com/spreadsheets/d/1uJ1gPo-apDgWLAbm_6CFfDYpV6ysfl33feItocuoP0c/edit#gid=1743949227)). Their status sheet looks something like this:

<img width="586" alt="image" src="https://user-images.githubusercontent.com/1976806/56215899-b87f7b00-6060-11e9-96b0-9275bb95d41e.png">

## Expected behavior

* Magic Spreadsheet projects the project's expected cash flow into the future. That is to say, it checks flows against the current date, discard everything that is in the past and builds a timeline of future cash availability based on the current bank account balance and future cash flows. 

* The projection cover the period "from today to the end of all active projects".

## Actual behavior

* Projects show as "finished" whenever a finishing date was entered into the MB, no matter if that date is in the past or the future:

    <img width="922" alt="image" src="https://user-images.githubusercontent.com/1976806/56216647-1b254680-6062-11e9-8c20-14bec92e041b.png">

* The margin is not imported into the MS.

* The visualization of the cash flow stops at the current date.

**Comment by tanius** [comment]
Fixed now.

On sheet "Overview", the project status will now be taken from "last entry before the current date in the Status sheet", and the information is then transferred from there to the Magic Spreadsheet (tested, works). The code assumes that records on sheet "Status" are sorted by date already. (Sorting on evaluation time could be added later, though.)

Again on sheet "Overview", the end date is now set independently from "first entry with status Finished in the Status sheet".

I applied the changes to the two budget sheets you're working on right now, to file "[Budget Template v3](https://docs.google.com/spreadsheets/d/1TYD2i8uycMb8pELSHG5T2wH1sJMP0T3RQsQ_iscKIYM/edit?usp=sharing)" and to all current "Budget Template v3: Placeholder Project …" files.
